name: challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.3.0
  get_storage: ^1.2.1
  dio: ^3.0.9
  flare_splash_screen: ^3.0.1
  equatable: ^1.2.2
  meta: ^1.1.8

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "coinsapp"
  image_path: "assets/coinsapp.png"

flutter:
  uses-material-design: true

  assets:
    - assets/intro.flr
